@startuml
!include ../style.puml

actor User

participant ":Ui" as Ui LOGIC_COLOR_T1
participant ":Parser" as Parser LOGIC_COLOR_T2
participant ":InvestmentList" as InvestmentList LOGIC_COLOR_T3
participant ":Investment" as Investment LOGIC_COLOR_T4

User -> Ui ++: list investment

Ui -> Parser ++: tryCommand(userInput)

Parser -> Parser ++: handleCommand(userInput)

Parser -> InvestmentList ++: listAllInvestments()

InvestmentList -> Ui ++: printAllInvestments(ArrayList<Investment>)
loop investment.size()
    Ui -> InvestmentList ++: investments.get(i:int)
    InvestmentList -> Investment ++: investment.toString()
    return investment:String
    return investment:String
    end
return

InvestmentList -> InvestmentList ++: getTotal5YearReturns()
return returns5Years:Double
InvestmentList -> InvestmentList ++: getTotal10YearReturns()
return returns10Years:Double

InvestmentList -> Ui ++: printInvestmentReturns(...)
note left: Params: returns5Years, returns10Years



return

return
return
return
return


@enduml