@startuml
!include ../style.puml

actor User

participant ":Ui" as Ui LOGIC_COLOR_T1
participant ":Parser" as Parser LOGIC_COLOR_T2
participant ":ExpenseList" as ExpenseList LOGIC_COLOR_T3
participant ":Expense" as Expense LOGIC_COLOR_T4

User -> Ui ++: delete expense

Ui -> Parser ++: tryCommand(userInput:String)
Parser -> Parser ++: handleCommand(userInput:String)

Parser -> Parser ++: parseDeleteExpenseCommand(userInput:String)
return indexToDelete:int

Parser -> ExpenseList ++: deleteExpense(indexToDelete:int)
ExpenseList -> Ui ++: printDeleteExpenseOutput(indexToDelete:int)
Ui -> Expense ++ : expense.toString()
return
return

ExpenseList -> Expense ++: expenses.remove()
return
destroy Expense


return
return
return
return

@enduml