@startuml
!include ../style.puml

actor User

participant ":Ui" as Ui LOGIC_COLOR_T1
participant ":Parser" as Parser LOGIC_COLOR_T2
participant ":LoanList" as LoanList LOGIC_COLOR_T3
participant ":Loan" as Loan LOGIC_COLOR_T4

User -> Ui ++: delete loan

Ui -> Parser ++: tryCommand(userInput:String)
Parser -> Parser ++: handleCommand(userInput:String)

Parser -> Parser ++: parseDeleteLoanCommand(userInput:String)
return indexToDelete:int

Parser -> LoanList ++: deleteLoan(indexToDelete:int)
LoanList -> LoanList ++: loans.get(indexToDelete:int)
return loan:Loan

LoanList -> Ui ++: printDeleteLoanOutput(loan:Loan)
Ui -> Loan ++: loan.toString()
return outputString:String
return

LoanList -> Loan ++: loans.remove()
return
destroy Loan


return
return
return
return

@enduml