!define LOGIC_COLOR #3333C4
!define LOGIC_COLOR_T1 #7777DB
!define LOGIC_COLOR_T2 #EE82EE
!define LOGIC_COLOR_T3 #90EE90
!define LOGIC_COLOR_T4 #FC9D03
!define LOGIC_COLOR_T5 #42CBF5
!define LOGIC_COLOR_T6 #F5E342
