@startuml
!include ../style.puml

actor User

participant ":Ui" as Ui LOGIC_COLOR_T1
participant ":Parser" as Parser LOGIC_COLOR_T2
participant ":ExpenseList" as ExpenseList LOGIC_COLOR_T3
participant ":Expense" as Expense LOGIC_COLOR_T4

User -> Ui ++: add expense

Ui -> Parser ++: tryCommand(userInput:String)

Parser -> Parser ++: handleCommand(userInput:String)

Parser -> Parser ++: parseAddExpenseCommand(userInput:String)
return commandParameters:String[]

create Expense
Parser -> Expense ++: new Expense(commandParameters:String[])
return expense:Expense

Parser -> ExpenseList ++: addExpense(commandParameters[])

ExpenseList -> Ui ++: printAddExpenseOutput(expense:Expense)

Ui -> Expense ++ : expense.toString()
return outputStringBuilder:String

return

return
return
return
return

@enduml