@startuml
!include ../style.puml

actor User

participant ":Ui" as Ui LOGIC_COLOR_T1
participant ":Parser" as Parser LOGIC_COLOR_T2
participant ":InvestmentList" as InvestmentList LOGIC_COLOR_T3
participant ":Investment" as Investment LOGIC_COLOR_T4

User -> Ui ++: list investment

Ui -> Parser ++: tryCommand(...)

Parser -> Parser ++: handleCommand(...)

Parser -> InvestmentList ++: listAllInvestments()

InvestmentList -> Ui ++: printAllInvestments(ArrayList<Investment>)
loop i from 0 to Investment.size() - 1
    Ui -> InvestmentList ++: investments.get(i:int)
    InvestmentList -> Investment ++: investment.toString()
    return investment:String
    return investment:String
    end
return

InvestmentList -> Ui ++: printInvestmentReturns(...)
return

return
return
return
return


@enduml