@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

object "{abstract}\n<<template>>\nDataManager<T,X>" as DM {
--
+ tryLoad(): ArrayList<T>
+ writeToFile(List<T>): void
+ appendToFile(T): void
# ensureFileExist(): void
# ensureParentDir(): void
# sanitize(String): String
# unsanitize(String): String

..{abstract}..
# parseRecord(String): T {abstract}
# formatRecord(T): String {abstract}
# dataFilePath(): Path {abstract}
}

object ChildDataManager {
--
# parseRecord(String): T
# formatRecord(T): String
# dataFilePath(): Path
}

note right of ChildDataManager: ChildDataManager includes:\nLoanDataManager, ExpenseDataManager,\nIncomeDataManager, InvestDataManager
DM <|-- ChildDataManager
@enduml