@startuml
!include ../style.puml

actor User

participant ":Ui" as Ui LOGIC_COLOR_T1
participant ":Parser" as Parser LOGIC_COLOR_T2
participant ":LoanList" as LoanList LOGIC_COLOR_T3
participant ":Loan" as Loan LOGIC_COLOR_T4

User -> Ui ++: add loan

Ui -> Parser ++: tryCommand(userInput:String)

Parser -> Parser ++: handleCommand(userInput:String)

Parser -> Parser ++: parseAddLoanCommand(userInput:String)
return commandParameters:String[]

create Loan
Parser -> Loan ++: new Loan(commandParameters:String[])
return loan:Loan

Parser -> LoanList ++: addLoan(loan:Loan)

LoanList -> Ui ++: printAddLoanOutput(loan:Loan)

Ui -> Loan ++: loan.toString()
return outputString:String

return

return
return
return
return

@enduml