@startuml
!include ../style.puml

actor User

participant ":Ui" as Ui LOGIC_COLOR_T1
participant ":Parser" as Parser LOGIC_COLOR_T2
participant ":LoanList" as LoanList LOGIC_COLOR_T3
participant ":Loan" as Loan LOGIC_COLOR_T4

User -> Ui ++: list loan

Ui -> Parser ++: tryCommand(userInput:String)

Parser -> Parser ++: handleCommand(userInput:String)

Parser -> Parser ++: parseLoanRepaidCommand(userInput:String)
return indexToSetRepaid:int

Parser -> LoanList ++: setRepaid(indexToSetRepaid:int)

LoanList -> LoanList ++: loans.get(indexToSetRepaid:int)
return loan:Loan

LoanList -> Loan ++: loan.setRepaid()
return

LoanList -> LoanList ++: loans.get(indexToSetRepaid:int)
return loan:Loan

LoanList -> Ui ++: printLoanRepaid(loan:Loan)
Ui -> Loan ++: loan.toString()
return outputString:String
return


return
return
return
return

@enduml