@startuml
!include style.puml

actor User

participant ":Ui" as Ui LOGIC_COLOR_T1
participant ":Parser" as Parser LOGIC_COLOR_T2
participant ":InvestmentList" as InvestmentList LOGIC_COLOR_T3
participant ":Investment" as Investment LOGIC_COLOR_T4
participant ":InvestDataManager" as DataManager LOGIC_COLOR_T2

User -> Ui ++: add investment

Ui -> Parser ++: tryCommand(...)

Parser -> Parser ++: handleCommand(...)

Parser -> Parser ++: parseAddInvestmentCommand(...)
return commandParameters:String[]

create Investment
Parser -> Investment ++: Investment(commandParameters[])
return

Parser -> InvestmentList ++: addInvestment(investment)


InvestmentList -> InvestmentList ++: add:investment
return
InvestmentList -> Ui ++: printAddInvestmentOutput(investments:ArrayList<Investment>)
return

InvestmentList -> DataManager ++: appendToFile(investment)
return

return
return
return
return

@enduml