@startuml
!include style.puml

actor User

participant ":Ui" as Ui LOGIC_COLOR_T1
participant ":Parser" as Parser LOGIC_COLOR_T2
participant ":LoanList" as LoanList LOGIC_COLOR_T3
participant ":Loan" as Loan LOGIC_COLOR_T4

User -> Ui ++: list loan

Ui -> Parser ++: tryCommand(userInput:String)

Parser -> Parser ++: handleCommand(userInput:String)

Parser -> LoanList ++: listLoans()

LoanList -> Ui ++: printAllLoans(loans)
loop Loan.numberOfLoans
    Ui -> LoanList ++: loans.get(index:int)
    LoanList -> Loan ++: loan.toString()
    return outputString:String
    return outputString:String
    end

return
return
return
return
return

@enduml