@startuml
!include ../style.puml

actor User

participant ":Ui" as Ui LOGIC_COLOR_T1
participant ":Parser" as Parser LOGIC_COLOR_T2
participant ":IncomeList" as IncomeList LOGIC_COLOR_T3
participant ":Income" as Income LOGIC_COLOR_T4

User -> Ui ++: add income
Ui -> Parser ++: tryCommand(...)
Parser -> Parser ++: handleCommand(...)
Parser -> Parser ++: parseAddLoanCommand(...)
return commandParameters: String[]

Parser -> IncomeList ++: addIncome(commandParameters[])
return income

create Income
IncomeList -> Income ++: new Income(commandParameters[])
return income

IncomeList -> Income ++: income.toString()
return income:String
IncomeList -> Ui ++: printAddIncomeOutput(income:String)
return

return
return
return

@enduml