@startuml
!include ../style.puml

actor User

participant ":Ui" as Ui LOGIC_COLOR_T1
participant ":Parser" as Parser LOGIC_COLOR_T2
participant ":IncomeList" as IncomeList LOGIC_COLOR_T3
participant ":Income" as Income LOGIC_COLOR_T4

User -> Ui ++: edit income
Ui -> Parser ++: tryCommand(...)
Parser -> Parser ++: handleCommand(...)
Parser -> Parser ++: parseEditIncomeCommand(...)
return commandParameters : String[]

Parser -> IncomeList ++: editIncome(commandParameters[])

IncomeList -> Income ++: income.toString()
return income:String

IncomeList -> Income ++: incomes.get().setDescription()
return

IncomeList -> Income ++: incomes.get().setAmountEarned()
return

IncomeList -> Ui ++: printEditIncomeOutput(income:String, commandParameters[0])
return

return
return
return
return

@enduml